services:
  # to automatically look for new image builds for all the services running below 
  watchtower:
    image: containrrr/watchtower
    command:
      - "--cleanup=true"
      - "--label-enable"
      - "--interval"
      - "120"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # for reverse proxy, load balancing and SSL certificate issuing 
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Access Docker
      - ./letsencrypt:/letsencrypt  # Store SSL certificates
    command:
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.email=hishamladha@gmail.com"  
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  # front end service ofc...
  frontend:
    image: ghcr.io/hishamladha/intern-salaries-frontend:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`salaries.hishamladha.com`)" 
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000" # FE port
      - "com.centurylinklabs.watchtower.enable=true"
  # backend service, ofc
  backend:
    image: ghcr.io/hishamladha/intern-salaries-backend:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - db
    deploy: # For running 3 identical containers simultaneously for load balancing with traefik
      # mode: replicated
      # replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 1200M
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.salaries.hishamladha.com`)"  
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"  # BE port
      - "com.centurylinklabs.watchtower.enable=true"
  # database, ofc
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
